### ISSUE TITLE
Support for nested paths (eg: for angular routing)

### ISSUE THREAD

**Issue by lf-novelt** [garybernhardt/static-path#4]
Hello Gary,

Any advice how can this library help support nested components routing using **angular-routing** style:

```js
  {
    path: "admin",
    component: AdminWrapperComponent,
    canActivate: [MsalGuard],
    children: [
      {
        path: "users",
        component: UsersAdminComponent,
        data: { title: 'UserAdministration' },
      },
      {
        path: "roles",
        component: RolesAdminComponent,
        data: { title: 'RolesAdministration' },
      },
      {
        path: `roles/:${APP_ROUTES_PARAMS.ROLE_ID}`, // 'roles/:id'
        component: RoleConfigureComponent,
        data: { title: 'Configure Role' },
      },
``` 

Then the app needs to generate strongly-typed links to `/admin/users`,  `/admin/roles` or  `/admin/roles/123` .
I guess I still have to smash some strings together at some point, right?

Doing something like
```js
let admin = path('/admin');
let roleId = path('/roles/:roleId')

let linkToRole = admin() + roleId({roleId: 123})

```

seems to defeat a bit the purpose, doesn't it?

**Comment by lf-novelt** [comment]
I guess I could declare all final paths (`let roleId = path('/admin/roles/:roleId')`) in my `paths.ts` and still export the partial path constants (`APP_SEGMENTS.admin = 'admin'`) for the router (` path: APP_SEGMENTS.admin,`) but that won't enforce typings in a big route refactor...

Note that flattening the routes structure has some impacts as the admin parent declares some wrapper component, so 
```
   path: "admin",
   children: {
      path: "users"
   }
```
in angular is not functionnaly the same as 
```
    path: "admin/users",
```

**Comment by garybernhardt** [comment]
Inability to flatten the routing table definitely makes this hard. What happens if you flatten the route patterns, but leave that canActivate in place? Does it still protect all of the patterns corresponding to its subpaths, even if they're not nested inside of its `children`?

If that's not possible and you require the canActivate guards, then I think that static-path is probably more trouble than it's worth. It's possible that static-path could accommodate this use case with some design change, but I don't know Angular so I wouldn't know where to start.

**Comment by lf-novelt** [comment]
Thanks for your reply.

What I ended up doing was to register all routes in the `paths.ts` in a flat way and use a function to redact the parent route from the child route in the hierarchical router declaration (it also removes the leading slash not authorized by angular)

`paths.ts`
```ts
export const x_admin = path(`/${APP_ROUTES_SEGMENTS.admin}`)
export const x_admin_users = path(`/${APP_ROUTES_SEGMENTS.admin}/${APP_ROUTES_SEGMENTS.users}`);
export const x_admin_roles = path(`/${APP_ROUTES_SEGMENTS.admin}/${APP_ROUTES_SEGMENTS.roles}`);
export const x_admin_role = path(`/${APP_ROUTES_SEGMENTS.admin}/${APP_ROUTES_SEGMENTS.roles}/:${APP_ROUTES_PARAMS.ROLE_ID}`);
```

`app-routings.ts`
```ts
function cleanRoutePattern(route: string, prefixToRemove = '') {
  return route.replace(prefixToRemove + '/', '');
}

export const APP_ROUTES: Routes = [
  {
    path: cleanRoutePattern(paths.x_admin.pattern), // returns '/admin' - '/' = 'admin'
    component: XmartAdminComponent,
    canActivate: [MsalGuard],
    children: [
      {
        path: cleanRoutePattern(paths.x_admin_users.pattern, paths.x_admin.pattern), // returns '/admin/users' - '/admin/' => 'users'
        component: UsersAdminComponent,
        data: { title: 'Users Administration' },
      },
      {
        path: cleanRoutePattern(paths.x_admin_roles.pattern, paths.x_admin.pattern),  // returns '/admin/roles' - '/admin/' => 'roles'
        pathMatch: "full",
        component: RolesAdminComponent,
        data: { title: 'Roles Administration' },
      },
      {
        path: cleanRoutePattern(paths.x_admin_role.pattern, paths.x_admin.pattern),  // returns '/admin/roles/:id' - '/admin/' => 'roles/:id'
        component: RoleConfigureComponent,
        data: { title: 'Configure Role' },
      },
```

Maybe I could have declared my paths using classes or object in a hierarchical way so that they are aware of their own parent, but at least now my routes are strongly typed!

Thanks a lot

**Comment by lf-novelt** [comment]
Note that in order to have strongly-typed param properties using those `APP_ROUTES_SEGMENTS.admin` variables, they have to be either explicitely typed like so: (rather than default type `string`)

```ts
export class APP_ROUTES_SEGMENTS {
  public static admin: 'admin' = 'admin'; // used to be of type string by default, which cannot be properly inferred by this lib
  public static roles = 'roles'; // not like this
  public static users: 'users' = 'users'; // like this: type is equal to its own value, not generic string
```
or marked as **readonly**

```ts
export class APP_ROUTES_SEGMENTS {
  public static readonly admin = 'admin'; 
  public static readonly roles = 'roles'; 
  public static readonly users = 'users'; // like this: type is equal to its own value, not generic string
```

**Comment by garybernhardt** [comment]
Glad you found a solution!
